name: Deploy BigQuery Queries
#comentário
on:
  push:
    branches:
      - main # ajuste de acordo com sua branch principal

jobs:
  deploy_queries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-bigquery google-cloud-bigquery-datatransfer

      - name: Modify Scheduled Query
        run: python scripts/modify_scheduled_query.py
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          QUERY_FILE: 'queries/precos-produtos.sql'
          SCHEDULED_QUERY_NAME: 'precos_produtos' # Ajuste para o nome exato da sua consulta agendada
