name: Deploy BigQuery Queries

on:
  push:
    branches:
      - main

jobs:
  deploy_queries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.0.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-bigquery google-cloud-bigquery-datatransfer

      - name: Modify Scheduled Query
        run: python scripts/modify_scheduled_query.py
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          QUERY_FILE: 'queries/precos-produtos.sql'
          SCHEDULED_QUERY_NAME: 'precos_produtos'
