name: Deploy BigQuery Queries

on:
  push:
    branches:
      - main # Isso indica que o workflow será executado em pushes para a branch 'main'

jobs:
  deploy_queries:
    runs-on: ubuntu-latest # Especifica que o job será executado no último Ubuntu disponível

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3 # Faz checkout do código do seu repositório

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3 # Configura o Google Cloud SDK
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }} # Usa a chave da conta de serviço armazenada nos segredos do GitHub
          project_id: ${{ secrets.GCP_PROJECT_ID }} # Define o ID do projeto
          export_default_credentials: true # Exporta as credenciais para serem usadas pelos comandos do gcloud

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip # Atualiza o pip
          pip install google-cloud-bigquery google-cloud-bigquery-datatransfer # Instala os pacotes do BigQuery

      - name: Modify Scheduled Query
        run: python scripts/modify_scheduled_query.py # Executa o script para modificar a consulta agendada
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} # Define o ID do projeto como uma variável de ambiente
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }} # Define a chave da conta de serviço como uma variável de ambiente
          QUERY_FILE: 'queries/precos-produtos.sql' # Define o arquivo da consulta SQL
          SCHEDULED_QUERY_NAME: 'precos_produtos' # Define o nome da consulta agendada
